### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by JustAGoodCow** [Leteroo/Epic7AutoBookmark_StoveClientVersion#1]
Traceback (most recent call last):
  File "main.py", line 623, in <module>
  File "main.py", line 523, in __init__
  File "main.py", line 573, in bind_worker
  File "main.py", line 94, in __init__
TypeError: cannot unpack non-iterable NoneType object

**Comment by Leteroo** [comment]
The name of window in the Traditional Chinese version had been fixed by SmileGate.  I have corrected the parameter in the program. Please redownload it.

**Comment by Leteroo** [comment]
And please note that this script only supports  Traditional Chinese version.  I might add other version in the future, maybe.
